### ISSUE TITLE
better with mods compatibility error 

### ISSUE THREAD

**Issue by silverhikari** [Mrthomas20121-Mods/TFCompat#5]
there is a problem when using better with mods with tfCompat
--------------------------------------------------------
exception caught during firing event net.minecraftforge.event.RegistryEvent$Register@449fa277:
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lnet.minecraft.item.ItemStack;
	at mrthomas20121.tfcompat.library.RecipeRegistry.convertStacks(RecipeRegistry.java:105) ~[RecipeRegistry.class:?]
	at mrthomas20121.tfcompat.compat.betterwithmods.BWMRegistry.millstoneRecipes(BWMRegistry.java:71) ~[BWMRegistry.class:?]
	at mrthomas20121.tfcompat.compat.betterwithmods.BWMRegistry.addRecipes(BWMRegistry.java:56) ~[BWMRegistry.class:?]
	at mrthomas20121.tfcompat.library.ModuleManager.onRegisterRecipesEvent(ModuleManager.java:80) ~[ModuleManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_385_ModuleManager_onRegisterRecipesEvent_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) ~[EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857) [GameData.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
-----------------------------------------------
mod versions used:
terrafirmacraft:1.7.10.168
tfcompat:1.2.0
rocksalt:1.0.3
betterwithmods:1.12-2.3.23
betterwithlib:1.12-1.5

**Comment by Mrthomas20121** [comment]
will look into it
